### ISSUE TITLE
CORI: Inline wysiwyg image not able to be formatted 

### ISSUE THREAD

**Issue by juliaford** [thinkshout/bene#145]
## Overview
When I placed the CORI mountain and tree svg in a rich text paragraph and centered it, it didn't work. It then doesn't allow me to add text (if I place the image first) but I should be able to move the image without having text. 

## This ticket is done when:
- [ ] item
- [ ] item

**Comment by heypaxton** [comment]
This is fixed

**Comment by tauno** [comment]
This looks like an issue still on CORI with their icon. It's aligning center but the `<article>` tag(s) are full width so it doesn't align in the center.

**Comment by heypaxton** [comment]
I fixed this with CSS. It sets a `text-align: center` on an embedded entity set to center.
